// Generated by Selenium IDE


import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class BabyClickMeSuitTest {

  //Proměná driver pomocí ovládáme stránku a získáváme informace
  private WebDriver driver;

  //Proměná URL je to naše domovská stránka
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","C:\\Users\\Michal\\Desktop\\JAVA\\chromedriver-win64\\chromedriver.exe");
    //System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver.exe");
    // create chrome option
    org.openqa.selenium.chrome.ChromeOptions cop = new org.openqa.selenium.chrome.ChromeOptions();
    // binary path
    cop.setBinary("C:\\Users\\Michal\\Desktop\\JAVA\\chrome-win64\\chrome.exe");

    driver = new  ChromeDriver(cop);
    js = (JavascriptExecutor) driver;

  }
  @After
  public void tearDown() {
    driver.quit();
  }


  @Test
  public void cklickmetwice() {
    driver.get("http://localhost/index.php");
    driver.manage().window().setSize(new Dimension(1936, 1066));
    driver.findElement(By.linkText("Click me baby")).click();
    driver.findElement(By.id("clickMe")).click();
    assertThat(driver.findElement(By.id("clicks")).getText(), is("1"));

    assertThat(driver.findElement(By.cssSelector(".description")).getText(), is("klik"));
  }
}
